apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 5m0s
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets-charts
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: "external-secrets@${GCP_PROJECT}.iam.gserviceaccount.com"
