apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  interval: 5m0s
  releaseName: api-gateway
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: api-gateway
      version: "0.1.16"
      sourceRef:
        kind: HelmRepository
        name: api-gateway
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/andreistefanciprian/api-gateway
      tag: 1.0.9@sha256:52e3ad73f5616b357d3000d640cc1650b0f2be79e07b560a81b36a2e2d0f7bd7
    config:
      LOG_LEVEL: DEBUG
      DOMAIN_NAME: ${CLOUDFLARE_DOMAIN}
      URL_GEN_HOST: url-gen.url-gen.svc
      URL_READ_HOST: url-read.url-read.svc
    httpRoute:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/exclude: "true"
      parentRefs:
        - name: urlshortener-gateway
          namespace: traefik-gateway
          sectionName: https-api-gateway
      hostnames:
        - ${CLOUDFLARE_DOMAIN}
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
              method: GET
