apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
spec:
  interval: 1m0s
  releaseName: secrets-store-csi-driver
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: 1.5.5
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
