apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-password
  namespace: url-read
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: redis-creds
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "${CLUSTER_NAME}-redis-password"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-creds
  namespace: url-read
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: pg-creds
    creationPolicy: Owner
  data:
    - secretKey: user-password
      remoteRef:
        key: "${CLUSTER_NAME}-db-user-password"
