apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: redis-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "${CLUSTER_NAME}-redis-password"
