apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: pg-creds
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: "${CLUSTER_NAME}-db-admin-password"
    - secretKey: user-password
      remoteRef:
        key: "${CLUSTER_NAME}-db-user-password"
    - secretKey: replication-password
      remoteRef:
        key: "${CLUSTER_NAME}-db-replication-password"
