
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra/gateway-api-crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system