apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: url-gen
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra/url-gen
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: namespaces
    - name: postgres
    - name: redis
    - name: external-secrets-config