apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m0s
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.19.4
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    global:
      priorityClassName: high-priority-nonpreempting
    installCRDs: true
    # When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted
    enableCertificateOwnerRef: true
    # Enable automatic certificate provisioning from Gateway API resources
    config:
      enableGatewayAPI: true
